/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as CustomTripsRouteImport } from './routes/custom-trips'
import { Route as WomenOnlyToursRouteImport } from './routes/women-only-tours'
import { Route as ApiChatRouteImport } from './routes/api.chat'
import { Route as DestinationsIndexRouteImport } from './routes/destinations.index'
import { Route as DestinationsSlugRouteImport } from './routes/destinations.$slug'
import { Route as TripsIndexRouteImport } from './routes/trips.index'
import { Route as TripsSlugRouteImport } from './routes/trips.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomTripsRoute = CustomTripsRouteImport.update({
  id: '/custom-trips',
  path: '/custom-trips',
  getParentRoute: () => rootRouteImport,
} as any)
const WomenOnlyToursRoute = WomenOnlyToursRouteImport.update({
  id: '/women-only-tours',
  path: '/women-only-tours',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const DestinationsIndexRoute = DestinationsIndexRouteImport.update({
  id: '/destinations/',
  path: '/destinations/',
  getParentRoute: () => rootRouteImport,
} as any)
const DestinationsSlugRoute = DestinationsSlugRouteImport.update({
  id: '/destinations/$slug',
  path: '/destinations/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const TripsIndexRoute = TripsIndexRouteImport.update({
  id: '/trips/',
  path: '/trips/',
  getParentRoute: () => rootRouteImport,
} as any)
const TripsSlugRoute = TripsSlugRouteImport.update({
  id: '/trips/$slug',
  path: '/trips/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/custom-trips': typeof CustomTripsRoute
  '/women-only-tours': typeof WomenOnlyToursRoute
  '/api/chat': typeof ApiChatRoute
  '/destinations/$slug': typeof DestinationsSlugRoute
  '/trips/$slug': typeof TripsSlugRoute
  '/destinations/': typeof DestinationsIndexRoute
  '/trips/': typeof TripsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/custom-trips': typeof CustomTripsRoute
  '/women-only-tours': typeof WomenOnlyToursRoute
  '/api/chat': typeof ApiChatRoute
  '/destinations/$slug': typeof DestinationsSlugRoute
  '/trips/$slug': typeof TripsSlugRoute
  '/destinations': typeof DestinationsIndexRoute
  '/trips': typeof TripsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/custom-trips': typeof CustomTripsRoute
  '/women-only-tours': typeof WomenOnlyToursRoute
  '/api/chat': typeof ApiChatRoute
  '/destinations/$slug': typeof DestinationsSlugRoute
  '/trips/$slug': typeof TripsSlugRoute
  '/destinations/': typeof DestinationsIndexRoute
  '/trips/': typeof TripsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/custom-trips'
    | '/women-only-tours'
    | '/api/chat'
    | '/destinations/$slug'
    | '/trips/$slug'
    | '/destinations/'
    | '/trips/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/custom-trips'
    | '/women-only-tours'
    | '/api/chat'
    | '/destinations/$slug'
    | '/trips/$slug'
    | '/destinations'
    | '/trips'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/custom-trips'
    | '/women-only-tours'
    | '/api/chat'
    | '/destinations/$slug'
    | '/trips/$slug'
    | '/destinations/'
    | '/trips/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CustomTripsRoute: typeof CustomTripsRoute
  WomenOnlyToursRoute: typeof WomenOnlyToursRoute
  ApiChatRoute: typeof ApiChatRoute
  DestinationsSlugRoute: typeof DestinationsSlugRoute
  TripsSlugRoute: typeof TripsSlugRoute
  DestinationsIndexRoute: typeof DestinationsIndexRoute
  TripsIndexRoute: typeof TripsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/custom-trips': {
      id: '/custom-trips'
      path: '/custom-trips'
      fullPath: '/custom-trips'
      preLoaderRoute: typeof CustomTripsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/women-only-tours': {
      id: '/women-only-tours'
      path: '/women-only-tours'
      fullPath: '/women-only-tours'
      preLoaderRoute: typeof WomenOnlyToursRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/destinations/': {
      id: '/destinations/'
      path: '/destinations'
      fullPath: '/destinations/'
      preLoaderRoute: typeof DestinationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/destinations/$slug': {
      id: '/destinations/$slug'
      path: '/destinations/$slug'
      fullPath: '/destinations/$slug'
      preLoaderRoute: typeof DestinationsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trips/': {
      id: '/trips/'
      path: '/trips'
      fullPath: '/trips/'
      preLoaderRoute: typeof TripsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trips/$slug': {
      id: '/trips/$slug'
      path: '/trips/$slug'
      fullPath: '/trips/$slug'
      preLoaderRoute: typeof TripsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CustomTripsRoute: CustomTripsRoute,
  WomenOnlyToursRoute: WomenOnlyToursRoute,
  ApiChatRoute: ApiChatRoute,
  DestinationsSlugRoute: DestinationsSlugRoute,
  TripsSlugRoute: TripsSlugRoute,
  DestinationsIndexRoute: DestinationsIndexRoute,
  TripsIndexRoute: TripsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
